// examples/react/src/components/ui/card.tsx
import type { HTMLAttributes } from 'react';

interface CardProps extends HTMLAttributes<HTMLDivElement> {}

export function Card({ className = '', children, ...props }: CardProps) {
  return (
    <div
      className={`border border-neutral-200 bg-white p-6 ${className}`}
      {...props}
    >
      {children}
    </div>
  );
}

// examples/solid/src/components/card.tsx
import { type JSX, splitProps } from 'solid-js';

interface CardProps extends JSX.HTMLAttributes<HTMLDivElement> {}

export function Card(props: CardProps) {
  const [local, others] = splitProps(props, ['class', 'children']);

  return (
    <div class={`border border-neutral-200 bg-white p-6 ${local.class || ''}`} {...others}>
      {local.children}
    </div>
  );
}
