// examples/svelte/src/lib/components/Card.svelte
<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements';
	import type { Snippet } from 'svelte';

	interface Props extends HTMLAttributes<HTMLDivElement> {
		class?: string;
		children?: Snippet;
	}

	let { class: className = '', children, ...props }: Props = $props();
</script>

<div class={`border border-neutral-200 bg-white p-6 ${className}`} {...props}>
	{@render children?.()}
</div>

// examples/react/src/components/card.tsx
import type { HTMLAttributes } from 'react';

interface CardProps extends HTMLAttributes<HTMLDivElement> {}

export function Card({ className = '', children, ...props }: CardProps) {
  return (
    <div className={`border border-neutral-200 bg-white p-6 ${className}`} {...props}>
      {children}
    </div>
  );
}
